feat: COM-2044 Исправил тестовую страницу для QA
CSSSR/qa-engineer pull request #1
Opened 2020-06-23 12:36 UTC by dyurein

2020-06-23 13:12 UTC, Yankovsky requested changes

2020-06-23 13:12 UTC, Yankovsky commented on index.html
> +
Почему удалил?

2020-06-23 13:12 UTC, Yankovsky commented on js/scripts.js
> +$(function() {
Зачем этот код про keyup? Можно просто работать с `value` или `$().val()` у полей, необязательно редактировать атрибут.

2020-06-23 13:28 UTC, dyurein commented on js/scripts.js
> +$(function() {
Я в css привязал translate лэйблов к input:not([value=""]), чтобы правильно отображалось

2020-06-23 13:30 UTC, Yankovsky commented on js/scripts.js
> +$(function() {
Ок

2020-06-23 14:15 UTC, dyurein commented on index.html
> +
Вернул

2020-06-23 14:19 UTC, Yankovsky approved these changes

2020-06-23 14:20 UTC, Yankovsky commented
Пока не мёрджи

2020-07-06 09:08 UTC, ArtyomResh commented
@Yankovsky Всё ещё пока не нужно мёрджить?

2020-07-06 10:07 UTC, Yankovsky commented
@ArtyomResh Да, пока ждём

2020-07-10 11:28 UTC, merged